---
labels:
  - name: kind:incomplete-template
    labeled:
      issue:
        body: |
          :wave: @{{ issue.user.login }}, please follow the template provided.
        action: close
        locking: lock
        lock_reason: resolved

  - name: kind:support
    labeled:
      issue:
        body: |
          :wave: @{{ issue.user.login }}, we use the issue tracker exclusively
          for bug reports and feature requests. 
        action: close

  - name: kind:incomplete-docs
    labeled:
      pr:
        body: |
          :wave: @{{ pull_request.user.login }}, thanks for taking the time to submit this PR. ğŸ™ğŸ½
          We have noticed that the chart documentation has not been completely updated for this PR.
          Could you please make sure that the following items have been updated:
          - `version` in `Chart.yaml` has been updated per [semver](http://semver.org/)
          - `README_CHANGELOG.md.gotmpl` contains a summary of the updates for this new version
          - [Documentation strings](https://github.com/norwoodj/helm-docs#valuesyaml-metadata) have been added to the keys in `values.yaml`.
          Afterwards you can run `./hack/gen-helm-docs.sh <chart>` again to update the chart's `README.md` file.
  - name: kind:incorrect-title
    labeled:
      pr:
        body: |
          :wave: @{{ pull_request.user.login }}, thanks for taking the time to submit this PR. ğŸ™ğŸ½
          We have noticed that the PR title does not adhere to our desired format.
          Could you please make sure that it follows the pattern `[<lowercase chart name>] <Update description>`?
          Example: `[radarr] Update image version`.
          Thanks!